//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by LAUNCHER.RC
//
#define IDI_LAUNCHER                    100
#define IDD_LAUNCHER                    101
#define IDC_SERVER                      1001
#define IDC_INFO                        1002
#define IDC_USERNAME                    1003
#define IDC_PASSWORD                    1004
#define IDC_SAVE_PASSWORD               1005
#define IDC_PLAY                        1006
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         201
#define _APS_NEXT_CONTROL_VALUE         1007
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
